services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - 5173:5173
      - 8080:8080
    stdin_open: true
    volumes:
      - .:/code
      - /code/node_modules
    restart: always
